name: Exploit Runner

on: [push]

jobs:
  exploit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run exploit
        run: |
          python3 speedrun.py
